name: Deploy
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: install Node.js
        uses: actions/setup-node@v4.0.0
        with: 
          node-version: "18.x"
      - name: install pnpm
        uses: pnpm/action-setup@v2.4.0
      - name: install deps
        run: pnpm i
      - name: build app
        run: pnpm run build
      - name: copy files to server
        uses: appleboy/scp-action@v0.0.1
        with:
          host: ${{secrets.REMOTE_HOST}}
          username: ${{secrets.REMOTE_USER}}
          passowrd: ${{secrets.REMOTE_PASSWORD}}
          port: 22
          source: "dist/"
          target: ${{secrets.REMOTE_TARGET}}
        
      
      
